# TODO ensure artefacts have limited lifetime on github packages
# TODO cancel current workflow if new run on the same branch, see https://stackoverflow.com/a/67939898
name: Build container image

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y wget
      - name: Install Apptainer
        run: |
          wget https://github.com/apptainer/apptainer/releases/download/v1.2.4/apptainer_1.2.4_amd64.deb
          sudo apt install -y ./apptainer_1.2.4_amd64.deb
          rm ./apptainer_1.2.4_amd64.deb
      - uses: actions/checkout@v4
      - name: Build container
        run: sudo apptainer build test.sif test.def
      - name: Login and deploy
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
          singularity push test.sif "oras://ghcr.io/${GITHUB_REPOSITORY}:${GITHUB_REF_NAME}"
